name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
   - name: Publish NuGet
  uses: rohith/publish-nuget@v2.2.1
  with:
    # Filepath of the project to be packaged, relative to root of repository
    PROJECT_FILE_PATH: 
    # Filepath containing version info, relative to root of repository. Defaults to `PROJECT_FILE_PATH` if not specified
    VERSION_FILE_PATH: # optional
    # Regex (with version in a capturing group) to extract the version from `VERSION_FILE_PATH`
    VERSION_REGEX: # optional, default is <Version>(.*)<\/Version>
    # Bypasses version resolution; useful for external providers like Nerdbank.GitVersioning
    VERSION_STATIC: # optional
    # Whether to create a tag when there's a version change
    TAG_COMMIT: # optional, default is true
    # Format of the tag, `*` is the placeholder for actual version
    TAG_FORMAT: # optional, default is v*
    # API key for the NuGet feed
    NUGET_KEY: # optional oy2glc3pur3lbg4qstjar3xj3evlbgzepn6j2oqatmxixq
    # NuGet package name, required when it's different from the project name
    PACKAGE_NAME: # optional
